dist: bionic
addons:
  apt:
    packages:
      - gcc
      - pkg-config
      - libwebkit2gtk-4.0-dev
      - make
      - wget
      - rpm

language: go
go:
  - "1.13"
env:
  - GO111MODULE=on

cache: pip
install:
  - pip install --user awscli
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/wadey/gocovmerge
  - go get golang.org/x/tools/cmd/goimports
  - make unshare
script:
  - make onedriver
  - bash .travis_lint.sh
  # we copy the auth_tokens for the test account to and from s3 each build.
  - aws s3 cp s3://fusefs-travis/.auth_tokens.json .
  - aws s3 cp s3://fusefs-travis/dmel.fa.gz .
  - gunzip dmel.fa.gz
  - go test -v -covermode=count -coverpkg=./fs/... -coverprofile=graph.coverage ./fs/graph
  - go test -v -covermode=count -coverpkg=./fs/... -coverprofile=fs.coverage ./fs
  # build test binary for ./offline with coverage enabled for ./fs,
  # then run tests offline
  - go test -c -covermode=count -coverpkg=./fs/... ./offline
  - sudo ./unshare -n -S $(id -u) -G $(id -g) ./offline.test -test.v -test.coverprofile=offline.coverage
after_script:
  - aws s3 cp .auth_tokens.json s3://fusefs-travis/
  - aws s3 cp fusefs_tests.log s3://fusefs-travis/
  - gocovmerge *.coverage > coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=all_coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

notifications:
  email: false
