# What log level should onedriver use (debug, info, and "warn" are recommended).
# - trace - Log everything, including every syscall handled by the filesystem.
# - debug - Log all operations that modify a file or directory.
# - info - Log "big" operations like uploads and downloads.
# - warn - These are warnings. Usually not a problem.
# - error - Things that onedriver doesn't like, but can continue running 
#          (can possibly result in file corruption or inability to do something).
# - fatal - Only log errors that kill the program (this log level is not recommended).
log: debug

# cacheDir specifies which directory onedriver should store its data in.
# This directory can get pretty large. "~" is a placeholder for your home directory.
cacheDir: ~/.cache/onedriver

# Don't uncomment or change this unless you are a super duper expert and have
# registered your own version of onedriver in Azure Active Directory. These are the
# default values.
#auth:
#  clientID: "3470c3fa-bc10-45ab-a0a9-2d30836485d1"
#	 codeURL: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize"
#  tokenURL: "https://login.microsoftonline.com/common/oauth2/v2.0/token"
#  redirectURL: "https://login.live.com/oauth20_desktop.srf"
